Repository DevCycleHQ/android-client-sdk, pull requests merged in 2023-05, with the labels that each got.

#145 [fix] ensure executor is active before starting EventSource
  android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DVCClient.kt
  android-client-sdk/src/main/java/com/devcycle/sdk/android/eventsource/EventSource.java
Labels: 1 min review

#146 [release] 1.4.4
  README.md
  android-client-sdk/build.gradle
Labels: 1 min review

#148 DVC-7156 Add variableValue() method, update tests, update example apps
  android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DVCClient.kt
  android-client-sdk/src/test/java/com/devcycle/sdk/android/api/DVCClientTests.kt
  java-example/src/main/java/com/devcycle/javaexample/JavaApplication.java
  kotlin-example/src/main/java/com/devcycle/example/KotlinApplication.kt
Labels: 5 min review

#149 [release] 1.5.0
  README.md
  android-client-sdk/build.gradle
Labels: 1 min review

#150 fix: on unknown exceptions, dont retry requests
  android-client-sdk/src/main/AndroidManifest.xml
  android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DVCApiClient.kt
  android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DVCClient.kt
  android-client-sdk/src/main/java/com/devcycle/sdk/android/api/DVCEdgeDBApiClient.kt
  android-client-sdk/src/main/java/com/devcycle/sdk/android/api/Request.kt
  android-client-sdk/src/main/java/com/devcycle/sdk/android/exception/NoNetworkException.kt
  android-client-sdk/src/main/java/com/devcycle/sdk/android/interceptor/NetworkConnectionInterceptor.kt
  android-client-sdk/src/test/java/com/devcycle/sdk/android/api/DVCClientTests.kt
  android-client-sdk/src/test/java/com/devcycle/sdk/android/api/EventQueueTests.kt
Labels: 5 min review

#151 chore(release): 1.6.0
  README.md
  android-client-sdk/build.gradle
Labels: 1 min review

#152 fix: Fix network available bug
  android-client-sdk/src/main/java/com/devcycle/sdk/android/interceptor/NetworkConnectionInterceptor.kt
  android-client-sdk/src/test/java/com/devcycle/sdk/android/interceptor/NetworkConnectionInterceptorTests.kt
Labels: 10 min review

#153 chore(release): 1.6.1
  README.md
  android-client-sdk/build.gradle
Labels: 1 min review
